FROM alpine:3.18

RUN apk add --no-cache \
    python3 \
    nodejs \
    npm \
    php82 \
    openjdk17 \
    busybox-extras \
    bash \
    build-base \
    curl \
    git

WORKDIR /workspace

CMD ["/bin/bash"]
